name = "Food Inno Circle site theme"
license = "Apache License 2.0"
licenselink = "//github.com/lumengxi/foodinnocircle-theme/blob/master/LICENSE"
description = "A one page portfolio for companies and freelancers."
homepage = "//github.com/lumengxi/foodinnocircle-theme"
tags = ["portfolio", "company", "contact form", "timeline", "google analytics", "piwik"]
min_version = 0.15

[author]
  name = "Mengxi Lu"
  homepage = "//github.com/lumengxi"

# If porting an existing theme
[original]
  name = "David Miller"
  homepage = "//www.ironsummitmedia.com/"
  repo = "//github.com/IronSummitMedia/startbootstrap-agency"
